name: Build & Release APK

on:
  push:
    tags:
      - 'v*'   # Triggers only on tags like v1.0, v1.2.3, etc.

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Grant execute permission for Gradle wrapper
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4. Build the release APK
      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: List built files
        run: ls -R app/build/outputs/apk/

      # 5. Upload artifact for debugging (optional)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      # 6. Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
